# action.yaml
# From https://betterprogramming.pub/4-steps-to-creating-a-custom-github-action-d67c4cf0445a
name: "Copied Custom Action"
description: "Call an API and get the result"
inputs:
  pokemon_id:
    description: "number of the pokemon in the pokedex"
    required: true
    default: 1
outputs:
  pokemon_name:
    description: "Name des Pokemons"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.pokemon_id}}
